name: Test
on:
  push:
    branches:
      - 'master'
jobs:
  test:
    name: Run tests, typechecks, and linter
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v4
      - name: Restore asdf cache
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
      - name: Install asdf
        uses: asdf-vm/actions/install@v3
      - name: Restore poetry cache
        id: poetry-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
      - name: Install Dependencies
        run: make deps
      - name: Run Tests
        run: make test_once
      - name: Run Typechecks
        run: make typeckeck
      - name: Run Linter
        run: make lint
